name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.ACR_PASSWORD }} | docker login sit72210dacr123.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

      # ===================== BACKEND SERVICES =====================
      - name: Build & Push Customer Service
        run: |
          docker build -t sit72210dacr123.azurecr.io/customer_service:latest ./backend/customer_service
          docker push sit72210dacr123.azurecr.io/customer_service:latest

      - name: Build & Push Order Service
        run: |
          docker build -t sit72210dacr123.azurecr.io/order_service:latest ./backend/order_service
          docker push sit72210dacr123.azurecr.io/order_service:latest

      - name: Build & Push Product Service
        run: |
          docker build -t sit72210dacr123.azurecr.io/product_service:latest ./backend/product_service
          docker push sit72210dacr123.azurecr.io/product_service:latest

      # ===================== FRONTEND =====================
      - name: Build & Push Frontend
        run: |
          docker build -t sit72210dacr123.azurecr.io/frontend:latest ./frontend
          docker push sit72210dacr123.azurecr.io/frontend:latest
