deploy_staging:
  name: Deploy to AKS Staging
  runs-on: ubuntu-latest
  needs: [build_and_push]   # only run if images built & pushed

  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set AKS context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        use-kubelogin: true

    - name: Create staging namespace
      run: |
        kubectl get ns staging || kubectl create ns staging

    - name: Deploy manifests
      run: |
        kubectl apply -f k8s/ -n staging
        kubectl rollout status deployment/frontend -n staging --timeout=180s
        kubectl rollout status deployment/customer-service -n staging --timeout=180s
        kubectl rollout status deployment/order-service -n staging --timeout=180s
        kubectl rollout status deployment/product-service -n staging --timeout=180s

    - name: Show frontend external IP
      run: |
        kubectl get svc frontend -n staging -o wide
