name: CI - Testing Branch

on:
  push:
    branches: ["testing"]
  pull_request:
    branches: ["testing"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: orders
        options: >-
          --health-cmd="pg_isready -U testuser -d orders"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      # Database connection string (used in db.py)
      DATABASE_URL: postgresql+psycopg2://testuser:testpassword@localhost:5432/orders

      # Mock service URLs for tests
      PRODUCT_SERVICE_URL: http://localhost:8002
      CUSTOMER_SERVICE_URL: http://localhost:8003

      # RabbitMQ (not used in tests, but set for completeness)
      RABBITMQ_HOST: localhost
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/order_service/requirements.txt
          pip install pytest httpx aio-pika psycopg2-binary

      - name: Wait for PostgreSQL
        run: |
          echo "⏳ Waiting for PostgreSQL to be ready..."
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U testuser -d orders && break
            sleep 3
          done

      - name: Run tests
        run: |
          cd backend/order_service
          pytest -v --disable-warnings --maxfail=1
