name: CI - Build and Push

on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # -------------------------
      # Checkout repository
      # -------------------------
      - name: Checkout repository
        uses: actions/checkout@v3

      # -------------------------
      # Setup Node.js for frontend
      # -------------------------
      - name: Set up Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Test frontend
        working-directory: ./frontend
        run: |
          npm install
          echo "✅ Frontend dependencies installed successfully"

      # -------------------------
      # Setup Python for backend
      # -------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies for backend
        run: |
          pip install --upgrade pip
          pip install pytest httpx sqlalchemy psycopg2-binary fastapi uvicorn

      # -------------------------
      # Run backend tests
      # -------------------------
      - name: Run Customer Service tests
        run: |
          cd backend/customer_service
          pip install -r requirements.txt
          pytest -q --disable-warnings --maxfail=1

      - name: Run Order Service tests
        run: |
          cd backend/order_service
          pip install -r requirements.txt
          pytest -q --disable-warnings --maxfail=1

      - name: Run Product Service tests
        run: |
          cd backend/product_service
          pip install -r requirements.txt
          pytest -q --disable-warnings --maxfail=1

      # -------------------------
      # Azure Login
      # -------------------------
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # -------------------------
      # ACR Login
      # -------------------------
      - name: ACR Login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      # -------------------------
      # Build Docker Images
      # -------------------------
      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest ./frontend
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/customer_service:latest ./backend/customer_service
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/order_service:latest ./backend/order_service
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/product_service:latest ./backend/product_service

      # -------------------------
      # Push Docker Images
      # -------------------------
      - name: Push Docker images
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/frontend:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/customer_service:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/order_service:latest
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/product_service:latest
