name: CI - Stage 1 (Testing Branch)

on:
  push:
    branches:
      - testing

env:
  ACR: ${{ secrets.ACR_LOGIN_SERVER }}
  IMAGE_TAG: ${{ github.sha }}
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: testdb
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/customers

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ---------- Setup DB ----------
      - name: Install Postgres client
        run: sudo apt-get install -y postgresql-client

      - name: Create test databases
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d testdb -c "CREATE DATABASE customers;"
          PGPASSWORD=postgres psql -h localhost -U postgres -d testdb -c "CREATE DATABASE orders;"
          PGPASSWORD=postgres psql -h localhost -U postgres -d testdb -c "CREATE DATABASE products;"

      # ---------- Backend Tests ----------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r backend/customer_service/requirements.txt
          pip install -r backend/order_service/requirements.txt
          pip install -r backend/product_service/requirements.txt
          pip install pytest psycopg2-binary

      - name: Run backend tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/customers
        run: |
          pytest backend/customer_service/tests --maxfail=1 --disable-warnings -q
          pytest backend/order_service/tests --maxfail=1 --disable-warnings -q
          pytest backend/product_service/tests --maxfail=1 --disable-warnings -q

      # ---------- Azure + ACR ----------
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: ACR Login
        run: az acr login --name ${{ env.ACR }}

      # ---------- Docker ----------
      - name: Build Docker images
        run: |
          docker build -t $ACR/frontend:${IMAGE_TAG} ./frontend
          docker build -t $ACR/customer_service:${IMAGE_TAG} ./backend/customer_service
          docker build -t $ACR/order_service:${IMAGE_TAG} ./backend/order_service
          docker build -t $ACR/product_service:${IMAGE_TAG} ./backend/product_service

      - name: Push Docker images
        run: |
          docker push $ACR/frontend:${IMAGE_TAG}
          docker push $ACR/customer_service:${IMAGE_TAG}
          docker push $ACR/order_service:${IMAGE_TAG}
          docker push $ACR/product_service:${IMAGE_TAG}
